apiVersion: apps/v1
kind: Deployment
metadata:
  name: krew-installer
spec:
  replicas: 3
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: replicated/node-pool
                operator: In
                values:
                - untrusted
      volumes:
        - name: sigsci
          hostPath:
            path: /var/run/sigsci
      containers:
        - name: krew-installer
          image: kotsadm/krew-installer
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/run/sigsci/
              name: sigsci
              readOnly: false
          env:
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: GIT_SHA
              value: "GIT_SHA_PLACEHOLDER"
            - name: AWS_REGION
              value: us-east-1
            - name: LOG_LEVEL
              value: debug
