steps:
  - label: build
    commands:
      - make deps build
    artifact_paths:
      - "bin/*"
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/replicatedhq/krew-installer

  - wait

  - label: build staging image
    commands:
      - mkdir -p bin
      - buildkite-agent artifact download bin/* bin/
      - buildkite-agent artifact download build/* build/
      - ls
      - make build-staging
    branches: master
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - label: build production image
    commands:
      - mkdir -p bin
      - buildkite-agent artifact download bin/* bin/
      - buildkite-agent artifact download build/* build/
      - ls
      - make build-production
    branches: master
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"

  - wait

  - commands:
      - make publish-staging
    branches: master
    retry:
      automatic:
        # this command exiting with status 2 typically means that the git commit collided with another
        - exit_status: 2
          limit: 5

  - block: "Release to production"
    branches: master

  - commands:
      - make publish-production
    branches: master
    retry:
      automatic:
        # this command exiting with status 2 typically means that the git commit collided with another
        - exit_status: 2
          limit: 5