apiVersion: v1
kind: Service
metadata:
  name: krew-installer
  labels:
    app: krew-installer
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30102
    port: 3000
    targetPort: http
  selector:
    app: krew-installer